version : '3'
services:
  mysql:
    image: mysql
    container_name: wallet-db
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: wallet
      MYSQL_ROOT_PASSWORD: 123
      # MYSQL_USER: admin
      # MYSQL_PASSWORD: admin
    ports:
      - "3308:3306"
    # volumes:
      # - "./scripts/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      # - "./scripts/data.sql:/docker-entrypoint-initdb.d/2.sql"